# Generated by Django 3.2.5 on 2021-07-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'Ветеринара', 'verbose_name_plural': 'Ветеринары'},
        ),
    ]
