# Generated by Django 3.2.5 on 2021-07-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doctors_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки'},
        ),
    ]
