# Generated by Django 3.2.5 on 2021-07-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
