# Generated by Django 3.2.5 on 2021-07-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_advice_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
