# Generated by Django 3.2.5 on 2021-07-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210710_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advice',
            name='picture',
        ),
    ]
