# Generated by Django 3.2.5 on 2021-07-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_advice_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
