# Generated by Django 3.2.5 on 2021-07-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210717_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Подробности')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('picture', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
            ],
        ),
    ]
