# Generated by Django 3.2.5 on 2021-07-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_feedback_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
