# Generated by Django 3.2.5 on 2021-08-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
