# Generated by Django 3.2.5 on 2021-09-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210907_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='star',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Рейтинг'),
        ),
    ]
