# Generated by Django 3.2.5 on 2021-09-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210909_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='star',
            field=models.IntegerField(max_length=5, null=True, verbose_name='Рейтинг'),
        ),
    ]
