# Generated by Django 3.2.5 on 2021-09-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_products_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='star',
            field=models.IntegerField(default=0, null=True, verbose_name='Рейтинг'),
        ),
    ]
