# Generated by Django 3.2.5 on 2021-09-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_products_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Соц.сети',
                'verbose_name_plural': 'Соц.сети',
            },
        ),
    ]
